<?php

return [
    'tr' => [
        'meta' => [
            'title' => 'SryyaLabs — Online Uygulamalar, Hazır Şablonlar ve Mobil Ürünler',
            'description' => 'SryyaLabs; günlük yaşamı ve iş süreçlerini kolaylaştıran online uygulamalar, hazır şablonlar ve mobil uygulamalar üreten bağımsız bir platform.',
        ],
        'nav' => [
            'services' => 'Ürün alanları',
            'approach' => 'Üretim süreci',
            'projects' => 'Ürünler',
            'about' => 'Hakkımızda',
            'blog' => 'Blog',
            'cta' => 'Ürünleri keşfet',
            'homeLabel' => 'SryyaLabs ana sayfa',
            'menuLabel' => 'Menüyü aç',
            'navLabel' => 'Ana menü',
            'languageLabel' => 'Dil seçimi',
        ],
        'hero' => [
            'eyebrow' => 'Bağımsız fikirler. Kullanışlı ürünler.',
            'line1' => 'Günlük hayat için',
            'accent' => 'dijital ürünler',
            'line3' => 'üretiyoruz.',
            'intro' => 'SryyaLabs; online uygulamalar, hazır şablonlar ve mobil uygulamalar üreten bir platform. Kendi fikirlerimizi, günlük yaşamda ve işinizde kullanabileceğiniz sade dijital ürünlere dönüştürüyoruz.',
            'cta' => 'Ürünleri keşfet',
            'work' => 'Ürün alanlarını incele',
            'aria' => 'SryyaLabs ürün platformu',
            'from' => 'Fikirden',
            'launch' => 'günlük kullanıma.',
            'disciplines' => 'web · şablon · mobil',
            'performance' => 'ürün alanı',
            'live' => 'Gelişim',
            'seamless' => 'sürekli iyileştirme',
            'proof' => [
                0 => 'Online uygulamalar',
                1 => 'Hazır şablonlar',
                2 => 'Mobil uygulamalar',
                3 => 'Sürekli gelişim',
            ],
        ],
        'services' => [
            'index' => '01 / ÜRÜN ALANLARI',
            'title1' => 'Farklı ihtiyaçlar için,',
            'title2' => 'kullanışlı ürünler.',
            'intro' => 'Tarayıcıda çalışan araçlardan hazır şablonlara ve mobil deneyimlere: SryyaLabs kendi ürünlerini tasarlar, geliştirir ve büyütür.',
            'items' => [
                0 => [
                    'no' => '01',
                    'title' => 'Online Uygulamalar',
                    'text' => 'Günlük işleri ve iş süreçlerini kolaylaştıran, tarayıcı üzerinden erişilebilen dijital araçlar ve platformlar.',
                ],
                1 => [
                    'no' => '02',
                    'title' => 'Hazır Şablonlar',
                    'text' => 'Yeni bir fikre daha hızlı başlamayı sağlayan, tekrar kullanılabilir arayüzler ve uygulama başlangıç şablonları.',
                ],
                2 => [
                    'no' => '03',
                    'title' => 'Mobil Uygulamalar',
                    'text' => 'Günlük yaşam, planlama ve kişisel iyi oluş için sade, akıcı ve kullanışlı mobil deneyimler.',
                ],
            ],
        ],
        'approach' => [
            'index' => '02 / ÜRETİM SÜRECİ',
            'title1' => 'Gerçek bir ihtiyaç.',
            'title2' => 'Yaşayan bir ürün.',
            'intro' => 'Her ürünümüzü belirli bir sorunu çözmek için geliştirir, kullanım deneyiminden öğrenerek iyileştiririz.',
            'steps' => [
                0 => [
                    'no' => '01',
                    'title' => 'İhtiyacı keşfet',
                    'text' => 'Günlük hayatta ve iş süreçlerinde tekrar eden sorunları araştırır, odaklanacağımız ihtiyacı belirleriz.',
                ],
                1 => [
                    'no' => '02',
                    'title' => 'Sadeleştir',
                    'text' => 'Ürünün temel faydasını öne çıkaran, kolay anlaşılır kullanım akışları tasarlarız.',
                ],
                2 => [
                    'no' => '03',
                    'title' => 'Üret ve yayınla',
                    'text' => 'Fikri çalışan bir uygulamaya veya yeniden kullanılabilir bir şablona dönüştürürüz.',
                ],
                3 => [
                    'no' => '04',
                    'title' => 'Öğren ve geliştir',
                    'text' => 'Kullanıcı geri bildirimleriyle ürünlerimizi günceller, deneyimi adım adım iyileştiririz.',
                ],
            ],
        ],
        'projects' => [
            'index' => '03 / ÜRÜNLER',
            'title' => 'SryyaLabs ürünleri.',
            'intro' => 'Yayındaki ve geliştirmekte olduğumuz ürünleri keşfedin. Her biri farklı bir ihtiyaca odaklanır.',
            'visit' => 'Ürünü incele',
            'previous' => 'Önceki ürün',
            'next' => 'Sonraki ürün',
            'carouselLabel' => 'SryyaLabs ürünleri',
            'items' => [
                0 => [
                    'slug' => 'bagla-app',
                    'name' => 'Bagla.app',
                    'type' => 'SaaS · İçerik araçları',
                    'description' => 'İçerik üreticileri ve işletmeler için bağlantıları tek yerde toplayan, ölçen ve yöneten akıllı profil platformu.',
                    'url' => 'https://bagla.app',
                    'logo' => '/images/projects/bagla-logo.jpg',
                    'note' => 'Bağlantılar · Analitik · Profil',
                ],
                1 => [
                    'slug' => 'claryflow',
                    'name' => 'ClaryFlow',
                    'type' => 'Mobil Uygulama · Mental Wellness',
                    'description' => 'Günlük yaşamda zihinsel iyi oluşu destekleyen, kişisel farkındalık ve dengeli rutinler oluşturmaya yardımcı olacak yeni nesil wellness uygulaması.',
                    'url' => '',
                    'logo' => '/images/projects/claryflow-logo.png',
                    'note' => 'Yakında',
                ],
                2 => [
                    'slug' => 'onlymlm',
                    'name' => 'OnlyMLM',
                    'type' => 'Platform · İş Yönetimi',
                    'description' => 'Network marketing operasyonlarının ekip, süreç ve performans yönetimini tek merkezden yürütmesine yardımcı olan dijital platform.',
                    'url' => 'https://onlymlm.com',
                    'logo' => '/images/projects/onlymlm-logo.png',
                    'note' => 'Ekip · Süreç · Büyüme',
                ],
                3 => [
                    'slug' => 'shiftcal',
                    'name' => 'ShiftCal',
                    'type' => 'Mobil Uygulama · Vardiya Planlama',
                    'description' => 'Vardiyalarınızı, çalışma saatlerinizi ve kazançlarınızı tek takvimde takip edin. Tekrar eden vardiya şablonları ve ortak planlarla iş ve günlük yaşamınızı daha kolay düzenleyin.',
                    'url' => '',
                    'logo' => '/images/projects/shiftcal-logo.png',
                    'note' => 'Geliştiriliyor',
                    'details_available' => false,
                ],
            ],
        ],
        'about' => [
            'index' => '04 / SRYYALABS',
            'title1' => 'Fikirler bize ait.',
            'title2' => 'Fayda herkes için.',
            'lead' => 'SryyaLabs, online uygulamalar, hazır şablonlar ve mobil uygulamalar üreten bağımsız bir dijital ürün platformudur.',
            'text' => 'Kendi ürünlerimize odaklanıyoruz. Amacımız, teknolojiyi günlük yaşamda işe yarayan, kolay erişilebilir ve uzun süre geliştirilebilen araçlara dönüştürmek.',
            'metrics' => [
                0 => [
                    0 => 'Web',
                    1 => 'online uygulamalar',
                ],
                1 => [
                    0 => 'Şablon',
                    1 => 'hazır başlangıçlar',
                ],
                2 => [
                    0 => 'Mobil',
                    1 => 'günlük deneyimler',
                ],
            ],
        ],
        'contact' => [
            'index' => '05 / İLETİŞİM',
            'title' => 'Ürünler hakkında konuşalım.',
            'text' => 'Uygulamalarımız ve şablonlarımız hakkında sorularınızı, önerilerinizi ve geri bildirimlerinizi bizimle paylaşın.',
            'subject' => 'SryyaLabs ürünleri hakkında',
        ],
        'footer' => [
            'tagline' => 'Online uygulamalar, hazır şablonlar ve mobil deneyimler.',
            'services' => 'Ürün alanları',
            'projects' => 'Ürünler',
            'contact' => 'İletişim',
        ],
    ],
    'en' => [
        'meta' => [
            'title' => 'SryyaLabs — Online Apps, Ready-Made Templates & Mobile Products',
            'description' => 'SryyaLabs is an independent platform creating online applications, ready-made templates and mobile apps for everyday life and work.',
        ],
        'nav' => [
            'services' => 'Product areas',
            'approach' => 'Our process',
            'projects' => 'Products',
            'about' => 'About',
            'blog' => 'Blog',
            'cta' => 'Explore products',
            'homeLabel' => 'SryyaLabs home page',
            'menuLabel' => 'Open menu',
            'navLabel' => 'Main navigation',
            'languageLabel' => 'Language selection',
        ],
        'hero' => [
            'eyebrow' => 'Independent ideas. Useful products.',
            'line1' => 'We create',
            'accent' => 'digital products',
            'line3' => 'for everyday life.',
            'intro' => 'SryyaLabs creates online applications, ready-made templates and mobile apps. We turn our own ideas into simple digital products you can use in everyday life and at work.',
            'cta' => 'Explore products',
            'work' => 'Explore product areas',
            'aria' => 'SryyaLabs product platform',
            'from' => 'From idea',
            'launch' => 'to everyday use.',
            'disciplines' => 'web · templates · mobile',
            'performance' => 'product areas',
            'live' => 'Evolving',
            'seamless' => 'continuous improvement',
            'proof' => [
                0 => 'Online applications',
                1 => 'Ready-made templates',
                2 => 'Mobile apps',
                3 => 'Continuous improvement',
            ],
        ],
        'services' => [
            'index' => '01 / PRODUCT AREAS',
            'title1' => 'Different needs.',
            'title2' => 'Useful products.',
            'intro' => 'From browser-based tools to ready-made templates and mobile experiences, SryyaLabs designs, builds and grows its own products.',
            'items' => [
                0 => [
                    'no' => '01',
                    'title' => 'Online Applications',
                    'text' => 'Digital tools and platforms accessible in your browser, designed to simplify everyday tasks and workflows.',
                ],
                1 => [
                    'no' => '02',
                    'title' => 'Ready-Made Templates',
                    'text' => 'Reusable interfaces and application starter templates that help you get a new idea moving faster.',
                ],
                2 => [
                    'no' => '03',
                    'title' => 'Mobile Applications',
                    'text' => 'Simple, fluid and useful mobile experiences for daily life, planning and personal wellbeing.',
                ],
            ],
        ],
        'approach' => [
            'index' => '02 / OUR PROCESS',
            'title1' => 'A real need.',
            'title2' => 'An evolving product.',
            'intro' => 'We build each product to solve a specific problem and improve it by learning from how people use it.',
            'steps' => [
                0 => [
                    'no' => '01',
                    'title' => 'Discover the need',
                    'text' => 'We explore recurring problems in daily life and work, then choose a clear need to focus on.',
                ],
                1 => [
                    'no' => '02',
                    'title' => 'Simplify',
                    'text' => 'We design easy-to-understand flows that keep the core benefit of the product in focus.',
                ],
                2 => [
                    'no' => '03',
                    'title' => 'Build and launch',
                    'text' => 'We turn the idea into a working application or a reusable template.',
                ],
                3 => [
                    'no' => '04',
                    'title' => 'Learn and improve',
                    'text' => 'User feedback helps us update our products and improve the experience step by step.',
                ],
            ],
        ],
        'projects' => [
            'index' => '03 / PRODUCTS',
            'title' => 'Products by SryyaLabs.',
            'intro' => 'Explore our live products and those in development. Each one focuses on a different need.',
            'visit' => 'Explore product',
            'previous' => 'Previous product',
            'next' => 'Next product',
            'carouselLabel' => 'SryyaLabs products',
            'items' => [
                0 => [
                    'slug' => 'bagla-app',
                    'name' => 'Bagla.app',
                    'type' => 'SaaS · Creator tools',
                    'description' => 'A smart profile platform that helps creators and businesses collect, manage and measure their links in one place.',
                    'url' => 'https://bagla.app',
                    'logo' => '/images/projects/bagla-logo.jpg',
                    'note' => 'Links · Analytics · Profile',
                ],
                1 => [
                    'slug' => 'claryflow',
                    'name' => 'ClaryFlow',
                    'type' => 'Mobile App · Mental Wellness',
                    'description' => 'A next-generation wellness app designed to support mental wellbeing, personal awareness and more balanced daily routines.',
                    'url' => '',
                    'logo' => '/images/projects/claryflow-logo.png',
                    'note' => 'Coming soon',
                ],
                2 => [
                    'slug' => 'onlymlm',
                    'name' => 'OnlyMLM',
                    'type' => 'Platform · Business Management',
                    'description' => 'A digital platform that helps network marketing operations manage teams, workflows and performance from one place.',
                    'url' => 'https://onlymlm.com',
                    'logo' => '/images/projects/onlymlm-logo.png',
                    'note' => 'Teams · Operations · Growth',
                ],
                3 => [
                    'slug' => 'shiftcal',
                    'name' => 'ShiftCal',
                    'type' => 'Mobile App · Shift Planning',
                    'description' => 'Track your shifts, working hours and earnings in one calendar. Organize work and everyday life with recurring shift templates and shared plans.',
                    'url' => '',
                    'logo' => '/images/projects/shiftcal-logo.png',
                    'note' => 'In development',
                    'details_available' => false,
                ],
            ],
        ],
        'about' => [
            'index' => '04 / SRYYALABS',
            'title1' => 'Our own ideas.',
            'title2' => 'Useful to everyone.',
            'lead' => 'SryyaLabs is an independent digital product platform creating online applications, ready-made templates and mobile apps.',
            'text' => 'We focus on our own products. Our aim is to turn technology into accessible, useful tools that can keep improving over time.',
            'metrics' => [
                0 => [
                    0 => 'Web',
                    1 => 'online applications',
                ],
                1 => [
                    0 => 'Templates',
                    1 => 'ready-made starters',
                ],
                2 => [
                    0 => 'Mobile',
                    1 => 'everyday experiences',
                ],
            ],
        ],
        'contact' => [
            'index' => '05 / CONTACT',
            'title' => 'Let’s talk about our products.',
            'text' => 'Share your questions, suggestions and feedback about our applications and templates.',
            'subject' => 'About SryyaLabs products',
        ],
        'footer' => [
            'tagline' => 'Online applications, ready-made templates and mobile experiences.',
            'services' => 'Product areas',
            'projects' => 'Products',
            'contact' => 'Contact',
        ],
    ],
    'ru' => [
        'meta' => [
            'title' => 'SryyaLabs — Онлайн-приложения, готовые шаблоны и мобильные продукты',
            'description' => 'SryyaLabs — независимая платформа, создающая онлайн-приложения, готовые шаблоны и мобильные приложения для жизни и работы.',
        ],
        'nav' => [
            'services' => 'Направления',
            'approach' => 'Наш процесс',
            'projects' => 'Продукты',
            'about' => 'О нас',
            'blog' => 'Блог',
            'cta' => 'Наши продукты',
            'homeLabel' => 'Главная страница SryyaLabs',
            'menuLabel' => 'Открыть меню',
            'navLabel' => 'Главное меню',
            'languageLabel' => 'Выбор языка',
        ],
        'hero' => [
            'eyebrow' => 'Независимые идеи. Полезные продукты.',
            'line1' => 'Создаём',
            'accent' => 'цифровые продукты',
            'line3' => 'для повседневной жизни.',
            'intro' => 'SryyaLabs создаёт онлайн-приложения, готовые шаблоны и мобильные приложения. Мы превращаем собственные идеи в простые цифровые продукты для жизни и работы.',
            'cta' => 'Наши продукты',
            'work' => 'Направления продуктов',
            'aria' => 'Платформа продуктов SryyaLabs',
            'from' => 'От идеи',
            'launch' => 'к использованию.',
            'disciplines' => 'веб · шаблоны · мобайл',
            'performance' => 'направления',
            'live' => 'Развитие',
            'seamless' => 'постоянное улучшение',
            'proof' => [
                0 => 'Онлайн-приложения',
                1 => 'Готовые шаблоны',
                2 => 'Мобильные приложения',
                3 => 'Постоянное развитие',
            ],
        ],
        'services' => [
            'index' => '01 / НАПРАВЛЕНИЯ',
            'title1' => 'Разные потребности.',
            'title2' => 'Полезные продукты.',
            'intro' => 'От браузерных инструментов до готовых шаблонов и мобильных приложений: SryyaLabs создаёт и развивает собственные продукты.',
            'items' => [
                0 => [
                    'no' => '01',
                    'title' => 'Онлайн-приложения',
                    'text' => 'Цифровые инструменты и платформы в браузере, упрощающие повседневные задачи и рабочие процессы.',
                ],
                1 => [
                    'no' => '02',
                    'title' => 'Готовые шаблоны',
                    'text' => 'Многоразовые интерфейсы и стартовые шаблоны приложений для быстрого воплощения новых идей.',
                ],
                2 => [
                    'no' => '03',
                    'title' => 'Мобильные приложения',
                    'text' => 'Простые и удобные мобильные решения для повседневной жизни, планирования и личного благополучия.',
                ],
            ],
        ],
        'approach' => [
            'index' => '02 / НАШ ПРОЦЕСС',
            'title1' => 'Реальная потребность.',
            'title2' => 'Развивающийся продукт.',
            'intro' => 'Каждый продукт решает конкретную задачу. Мы улучшаем его, изучая опыт пользователей.',
            'steps' => [
                0 => [
                    'no' => '01',
                    'title' => 'Изучаем потребность',
                    'text' => 'Исследуем повторяющиеся проблемы в жизни и работе и выбираем конкретную задачу.',
                ],
                1 => [
                    'no' => '02',
                    'title' => 'Упрощаем',
                    'text' => 'Создаём понятные сценарии, раскрывающие основную пользу продукта.',
                ],
                2 => [
                    'no' => '03',
                    'title' => 'Создаём и выпускаем',
                    'text' => 'Превращаем идею в работающее приложение или многоразовый шаблон.',
                ],
                3 => [
                    'no' => '04',
                    'title' => 'Учимся и развиваем',
                    'text' => 'Обновляем продукты на основе обратной связи и постепенно улучшаем опыт использования.',
                ],
            ],
        ],
        'projects' => [
            'index' => '03 / ПРОДУКТЫ',
            'title' => 'Продукты SryyaLabs.',
            'intro' => 'Познакомьтесь с нашими действующими и разрабатываемыми продуктами. Каждый решает свою задачу.',
            'visit' => 'О продукте',
            'previous' => 'Предыдущий продукт',
            'next' => 'Следующий продукт',
            'carouselLabel' => 'Продукты SryyaLabs',
            'items' => [
                0 => [
                    'slug' => 'bagla-app',
                    'name' => 'Bagla.app',
                    'type' => 'SaaS · Инструменты для авторов',
                    'description' => 'Умная платформа профилей для авторов и компаний: все ссылки, управление и аналитика в одном месте.',
                    'url' => 'https://bagla.app',
                    'logo' => '/images/projects/bagla-logo.jpg',
                    'note' => 'Ссылки · Аналитика · Профиль',
                ],
                1 => [
                    'slug' => 'claryflow',
                    'name' => 'ClaryFlow',
                    'type' => 'Мобильное приложение · Mental Wellness',
                    'description' => 'Wellness-приложение нового поколения для поддержки ментального благополучия, осознанности и сбалансированных повседневных привычек.',
                    'url' => '',
                    'logo' => '/images/projects/claryflow-logo.png',
                    'note' => 'Скоро',
                ],
                2 => [
                    'slug' => 'onlymlm',
                    'name' => 'OnlyMLM',
                    'type' => 'Платформа · Управление бизнесом',
                    'description' => 'Цифровая платформа для централизованного управления командами, процессами и эффективностью в сетевом маркетинге.',
                    'url' => 'https://onlymlm.com',
                    'logo' => '/images/projects/onlymlm-logo.png',
                    'note' => 'Команды · Процессы · Рост',
                ],
                3 => [
                    'slug' => 'shiftcal',
                    'name' => 'ShiftCal',
                    'type' => 'Мобильное приложение · Планирование смен',
                    'description' => 'Следите за сменами, рабочими часами и заработком в одном календаре. Планируйте работу и повседневную жизнь с повторяющимися шаблонами смен и совместными планами.',
                    'url' => '',
                    'logo' => '/images/projects/shiftcal-logo.png',
                    'note' => 'В разработке',
                    'details_available' => false,
                ],
            ],
        ],
        'about' => [
            'index' => '04 / SRYYALABS',
            'title1' => 'Наши идеи.',
            'title2' => 'Польза для каждого.',
            'lead' => 'SryyaLabs — независимая платформа цифровых продуктов: онлайн-приложений, готовых шаблонов и мобильных приложений.',
            'text' => 'Мы сосредоточены на собственных продуктах. Наша цель — превращать технологии в доступные и полезные инструменты, которые можно постоянно развивать.',
            'metrics' => [
                0 => [
                    0 => 'Веб',
                    1 => 'онлайн-приложения',
                ],
                1 => [
                    0 => 'Шаблоны',
                    1 => 'готовые основы',
                ],
                2 => [
                    0 => 'Мобайл',
                    1 => 'ежедневный опыт',
                ],
            ],
        ],
        'contact' => [
            'index' => '05 / КОНТАКТЫ',
            'title' => 'Поговорим о продуктах.',
            'text' => 'Делитесь вопросами, предложениями и отзывами о наших приложениях и шаблонах.',
            'subject' => 'О продуктах SryyaLabs',
        ],
        'footer' => [
            'tagline' => 'Онлайн-приложения, готовые шаблоны и мобильные решения.',
            'services' => 'Направления',
            'projects' => 'Продукты',
            'contact' => 'Контакты',
        ],
    ],
];
